# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: srybi
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Business Information Systems Student
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#social media
twitter_username: DieserStefan  
github_username:  srybi
linkedin_username: Stefan Rybinski

#images
heroimage: https://free4kwallpapers.com/uploads/wallpaper/galaxy-background-1280x720-wallpaper.jpg
favicon-url: /assets/images/favicon-16x16.png


# author setting
author-name: Stefan Rybinski
# URL for the Image of the Author
author-image: assets/images/profiel.jpg
# 60 Words About the Author
author-about: >- 
  Hey! My name is Stefan and I study Business Information Systems at the University of Applied Sciences in Rosenheim. 
  Since my beginnings in 2019, I've been supported by HEIDENHAIN, a German manufactur for precision measurement.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 


# Build settings
markdown: GFM
remote_theme: thedevslot/WhatATheme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-admin

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/