# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: srybi
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Business Information Systems Student
baseurl:  # the subpath of your site, e.g. /blog
url: "http://srybi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#social media
twitter_username: DieserStefan  
github_username:  srybi
linkedin_username: stefan-rybinski-982026215/

#images
heroimage: /assets/images/hero.jpg
favicon-url: /assets/images/favicon-16x16.png


# author setting
author-name: Stefan Rybinski
# URL for the Image of the Author
author-image: https://media-exp1.licdn.com/dms/image/C4E03AQEagaxVFIp_gw/profile-displayphoto-shrink_800_800/0/1631789402479?e=1637193600&v=beta&t=VWuLVzD0-dviQrABMrEVj_90XO3M5SeaoSNfD4uMNLY
# 60 Words About the Author
author-about: |
  My name is Stefan Rybinski and I study Business Information Systems at the Rosenheim University of Applied Sciences. 
  Since my beginnings in 2019, I've been supported by HEIDENHAIN, a German manufacturer for precision measurement.
  For more information about my experience, read my <a class='in_text_link 'href='./portfolio/experience'>first portfolio post</a>. In 1999 my parents decided to move from Russia
  to a small Bavarian village near Munich. I grew up biligual: talking Russian at home and learning German in school.
  My hobbies are playing football, meeting friends and listening to Hip hop music.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# Build settings
markdown: GFM
remote_theme: thedevslot/WhatATheme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-admin

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Permalink
permalink: "portfolio/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/